### ISSUE TITLE
AMS parameters

### ISSUE THREAD

**Issue by delyank** [LLNL/parelag#10]
https://github.com/LLNL/parelag/blob/b95d355d320d586011fb1de92a60bca1964dc02f/src/linalg/solver_ops/ParELAG_AMSSolverWrapper.cpp#L88

This seems odd and incorrect. Shouldn't this actually be a call to `HYPREAMSSetBetaAMGOptions()` or I'm confusing something and the code is correct in its current state?

**Comment by barker29** [comment]
I think you're right. If you make a PR to fix I'd appreciate it - otherwise I will eventually do it.

**Comment by delyank** [comment]
I'll submit a fix, only wanted to make sure I didn't confuse myself too much. Such a chnage may affect the behavior of some previous tests because parameters that previously had no effect may no kick in and people may be surprised. But still it has to be correct.
